### ISSUE TITLE
Missing contact details

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#12]
The contact details are missing from the contact page.
![image](https://user-images.githubusercontent.com/97726944/168551735-7e90484d-38b8-4981-8a66-dc00fe0f9bc7.png)

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/168747717-6238def4-62c9-4efc-ba15-c60ada949bec.png)

**Comment by Shoaibans** [comment]
![image](https://user-images.githubusercontent.com/97726944/168771812-7731ad07-9e06-4352-89fb-dd51226c361a.png)
The spacing can be reduced
