### ISSUE TITLE
Accordion/ arrow buttons in prescription form

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#16]
The accordion/ arrow button in prescription form is not working on click.
![image](https://user-images.githubusercontent.com/97726944/168553420-f4e047f9-04fa-45f1-9177-292ab98aebb0.png)
Video: https://www.awesomescreenshot.com/video/8920980?key=4274ad82e4a153100854825eb303228f

**Comment by Shoaibans** [comment]
@devAbhishekYadav the accordions are not closing, pls leave a comment as per the discussion

**Comment by devAbhishekYadav** [comment]
the accordion would not close as per the reference as shared by client
