### ISSUE TITLE
Prescription accordion in product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#17]
The prescription form is not coming except glasses products, if not required on other products then we can remove the prescription from the other collections/products.
Video: https://www.awesomescreenshot.com/video/8921057?key=462bc6173b5615c56a991e2b03686b61

**Comment by devAbhishekYadav** [comment]
@Shoaibans it was to be done on my Part, not @ui-muskandwivedi . 
I have resolved it.
