### ISSUE TITLE
Cursor on hover

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#2]
Mouse cursor is coming while hovering to the search drop down & content in it.
There should be a hand cursor on hover.
![image](https://user-images.githubusercontent.com/97726944/168544286-503ff4c0-6252-4318-9a3e-6087ea62fd5b.png)

**Comment by ui-muskandwivedi** [comment]
dropdown list is in option tag and on that css would not work. 

"This is because this type of element is an example of a "replaced element". They are OS-dependent and are not part of the HTML/browser. It cannot be styled via CSS"(stack-overflow)
