### ISSUE TITLE
Unorganized content in quick view

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#20]
In some of the products, the description content is coming unorganized.
![image](https://user-images.githubusercontent.com/97726944/168556336-067f6041-0199-40a4-a0b7-fa10a5bd9338.png)
![image](https://user-images.githubusercontent.com/97726944/168564522-a254cb52-28cd-48e1-8dd5-cf803f7a8526.png)

**Comment by ui-muskandwivedi** [comment]
![2022-05-16](https://user-images.githubusercontent.com/100340361/168568913-388b669f-d099-423a-b83c-1889cd529ec7.png)

**Comment by ui-muskandwivedi** [comment]
product description is updated by the client.
