### ISSUE TITLE
Accordions sign/symbol in footer/ hamburger

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#32]
In footer, for opening the accordion there is an arrow button but for closing there is a - sign.
![image](https://user-images.githubusercontent.com/97726944/168563161-859da8cd-a5af-42c9-be1a-b32f238d8842.png)

Same in the Hamburger.
![image](https://user-images.githubusercontent.com/97726944/168563793-a480ead6-fc18-4d97-8b4f-34506297cc79.png)

**Comment by ui-muskandwivedi** [comment]
this is theme accordion.
