### ISSUE TITLE
Missing banners from the iPad homepage

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#33]
the banners are not reflecting in iPad 
![image](https://user-images.githubusercontent.com/97726944/168565263-427f98fc-f387-4d3f-91f8-41f74bf0c612.png)

**Comment by ui-muskandwivedi** [comment]
![2022-05-16 (2)](https://user-images.githubusercontent.com/100340361/168595429-100f0c95-6605-44d9-8c1c-21fa20b232f3.png)

**Comment by ui-muskandwivedi** [comment]
![2022-05-16 (3)](https://user-images.githubusercontent.com/100340361/168595529-00c605fa-d698-41f8-ac1d-90ca092ba4c0.png)

**Comment by ui-muskandwivedi** [comment]
![2022-05-16 (4)](https://user-images.githubusercontent.com/100340361/168595614-8187d680-3b0b-4eff-90f6-a1f583ead97c.png)
