### ISSUE TITLE
Missing sortby filter from search page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#35]
The sortby filters are missing from the search page.
![image](https://user-images.githubusercontent.com/97726944/168567049-3df8e47d-ab31-4c53-8a1f-fb955f2c3f7b.png)

**Comment by devAbhishekYadav** [comment]
the theme itself does not provide the option to add sort by options on the search page.

**Comment by Shoaibans** [comment]
@devAbhishekYadav now the existing filters are not coming on the search page.
![image](https://user-images.githubusercontent.com/97726944/168789960-96cdb198-0386-4742-8d73-0e71550507ee.png)

**Comment by devAbhishekYadav** [comment]
same case here you searched for glass and the results contain 1368 products which are more significant than 1000 so no filters.
