### ISSUE TITLE
Quick view & ATC on You may also like products  

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#37]
The Quick view & ATC on You may also like products are overlapping with the footer section.
![image](https://user-images.githubusercontent.com/97726944/168568021-67b9b357-7f2d-41b0-a512-6316f7124714.png)

**Comment by ui-muskandwivedi** [comment]
overlapping is happening due to theme hover effect and both buttons doesn't cover any footer content.
