### ISSUE TITLE
Missing filters

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#45]
The filters are missing from the collections/all page.
https://k9oqumg1zg9pq30n-8066629747.shopifypreview.com/collections/all
![image](https://user-images.githubusercontent.com/97726944/168786590-749da0e7-1913-4636-a25e-b71547721d93.png)

**Comment by devAbhishekYadav** [comment]
filters does not come to collections having products greater than 1000.

**Comment by Shoaibans** [comment]
@devAbhishekYadav Then the word "filter" should not be there
