### ISSUE TITLE
Spacing in quick view

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Zohra-Store-Dev#6]
We can reduce the spacing in quick view.

![image](https://user-images.githubusercontent.com/97726944/168547231-0b878c78-f291-4aa8-bb35-b7b5c1dc8f46.png)

**Comment by Shoaibans** [comment]
@ui-muskandwivedi pls leave a comment as per the discussion

**Comment by ui-muskandwivedi** [comment]
product description coming the same as updated by the client so as spacing
